<?xml version="1.0"?>
<package format="3">
  <name>mono_camera_calibration</name>
  <version>0.1.0</version>
  <description>Composable C++ monocular camera calibration with a lightweight GUI.</description>
  <maintainer email="fzhang859@connect.hkust-gz.edu.cn">pnx</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>cv_bridge</depend>
  <depend>diagnostic_msgs</depend>
  <depend>rclcpp</depend>
  <depend>rclcpp_components</depend>
  <depend>sensor_msgs</depend>
  <depend>std_srvs</depend>
  <depend>libopencv-dev</depend>

  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <test_depend>ament_cmake_gtest</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
